/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.reusingthewheel.languageGeneratorFramework

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
